# Generated by Django 3.1.6 on 2021-03-10 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=1, max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(default=1, unique=True)),
                ('description', models.TextField(default=1, verbose_name='Описание')),
                ('price', models.IntegerField(default=1, verbose_name='Цена')),
                ('photo', models.ImageField(default=1, upload_to='photos/%Y/%m/%d/')),
                ('animal', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата создания')),
                ('totalProducts', models.PositiveIntegerField(default=0)),
                ('finalPrice', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.IntegerField(verbose_name='Цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='orders.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=1, max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(default=1, unique=True)),
                ('description', models.TextField(default=1, verbose_name='Описание')),
                ('price', models.IntegerField(default=1, verbose_name='Цена')),
                ('photo', models.ImageField(default=1, upload_to='photos/%Y/%m/%d/')),
                ('size', models.CharField(max_length=5, verbose_name='Размер одежды')),
                ('season', models.CharField(max_length=10, verbose_name='Сезон')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер пользователя')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('us', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
            ],
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='orders.CartProduct'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.category'),
        ),
    ]
