# Generated by Django 3.1.6 on 2021-03-11 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210310_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='description',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='id',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='price',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='title',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='price',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='title',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=1, max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(default=1, unique=True)),
                ('description', models.TextField(default=1, verbose_name='Описание')),
                ('price', models.IntegerField(default=1, verbose_name='Цена')),
                ('photo', models.ImageField(default=1, upload_to='photos/%Y/%m/%d/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.category')),
            ],
        ),
        migrations.AddField(
            model_name='accessories',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.product'),
            preserve_default=False,
        ),
    ]
