# Generated by Django 3.1.6 on 2021-02-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210212_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='departureDate',
        ),
    ]
