# Generated by Django 3.1.6 on 2021-03-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210311_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='animal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='season',
            field=models.CharField(blank=True, max_length=10, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(blank=True, max_length=5, verbose_name='Розмір одягу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Опис товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=500, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Назва продукту', max_length=255),
        ),
    ]
