# Generated by Django 3.1.6 on 2021-04-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_customer_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='orders.Order', verbose_name='Заказы покупателя'),
        ),
    ]
