# Generated by Django 3.1.6 on 2021-02-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210212_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sclad',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='us',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.customer'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
