# Generated by Django 3.1.6 on 2021-04-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customer_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=75, null=True)),
                ('title', models.CharField(default='Назва продукту', max_length=255)),
                ('slug', models.SlugField(default=1, unique=True)),
                ('description', models.TextField(blank=True, default='Опис товару')),
                ('price', models.IntegerField(default=500, verbose_name='Ціна')),
                ('photo', models.ImageField(default=1, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
