# Generated by Django 3.1.6 on 2021-03-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210311_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='product_ptr',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.category'),
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
    ]
