# Generated by Django 3.1.6 on 2021-04-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_newproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
